language: python
sudo: false
python:
  - "3.6"
addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py develop
script:
  - nosetests --with-coverage --cover-package=jetpack --logging-level=INFO
cache:
    - apt
    - directories:
        - $HOME/.cache/pip
after_success:
  - coveralls
